diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=renjusk
user.email=rkarunakaran@cloud3tech.com
merge.tool=ultracompare
mergetool.ultracompare.keepbackup=false
mergetool.ultracompare.trustexitcode=false
mergetool.ultracompare.prompt=false
mergetool.ultracompare.cmd="C:\Program Files\IDM Computer Solutions\UltraCompare\uc.exe" -gitm $LOCAL $REMOTE $BASE $MERGED -title1 LOCAL -title2 REMOTE
uc.defdiffmerge=yes
uc.defdiff=yes
diff.tool=ultracompare
difftool.ultracompare.keepbackup=false
difftool.ultracompare.trustexitcode=false
difftool.ultracompare.prompt=false
difftool.ultracompare.cmd="C:\Program Files\IDM Computer Solutions\UltraCompare\uc.exe" -gitdt $LOCAL $REMOTE $BASE $MERGED -title1 LOCAL -title2 REMOTE
http.postbuffer=524288000
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/skrenju/Demo.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
